### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by chaolixu** [muschellij2/extrantsr#13]
I can't install "extrantsr" package in my R package. it said the package had non-zero exit status.

make[6]: *** [Examples/antsApplyTransformsToPoints] Error 1
make[6]: Leaving directory '/tmp/Rtmp652CYB/R.INSTALL5eb24bc652e7/ANTsRCore/src/antb/ANTS-build'
CMakeFiles/Makefile2:577: recipe for target 'Examples/CMakeFiles/antsApplyTransformsToPoints.dir/all' failed
make[5]: *** [Examples/CMakeFiles/antsApplyTransformsToPoints.dir/all] Error 2
make[5]: *** Waiting for unfinished jobs....
[ 41%] Linking CXX static library libl_antsAffineInitializer.a
make[6]: Leaving directory '/tmp/Rtmp652CYB/R.INSTALL5eb24bc652e7/ANTsRCore/src/antb/ANTS-build'
[ 41%] Built target l_antsAffineInitializer
make[5]: Leaving directory '/tmp/Rtmp652CYB/R.INSTALL5eb24bc652e7/ANTsRCore/src/antb/ANTS-build'
Makefile:162: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/tmp/Rtmp652CYB/R.INSTALL5eb24bc652e7/ANTsRCore/src/antb/ANTS-build'
CMakeFiles/ANTS.dir/build.make:113: recipe for target 'ANTS-prefix/src/ANTS-stamp/ANTS-build' failed
make[3]: *** [ANTS-prefix/src/ANTS-stamp/ANTS-build] Error 2
make[3]: Leaving directory '/tmp/Rtmp652CYB/R.INSTALL5eb24bc652e7/ANTsRCore/src/antb'
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/ANTS.dir/all' failed
make[2]: *** [CMakeFiles/ANTS.dir/all] Error 2
make[2]: Leaving directory '/tmp/Rtmp652CYB/R.INSTALL5eb24bc652e7/ANTsRCore/src/antb'
Makefile:116: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/tmp/Rtmp652CYB/R.INSTALL5eb24bc652e7/ANTsRCore/src/antb'
Makevars:12: recipe for target 'libs' failed
make: *** [libs] Error 2
ERROR: compilation failed for package 'ANTsRCore'
* removing '/opt/tacc_mounts/home1/06852/chaolixu/lib64/R/library/ANTsRCore'
* restoring previous '/opt/tacc_mounts/home1/06852/chaolixu/lib64/R/library/ANTsRCore'
Error: Failed to install 'ANTsR' from GitHub:
Failed to install 'ANTsRCore' from GitHub:
(converted from warning) installation of package '/tmp/RtmpkXj1fU/file2b1948b4c199/ANTsRCore_0.7.3.tar.gz' had non-zero exit status
Appreciate any help!

**Comment by muschellij2** [comment]
This is an ANTsRCore issue, not an extrantsr, please open an issue at https://github.com/ANTsX/ANTsRCore/issues with the full installation code:

**Comment by chaolixu** [comment]
Hi, Pro. Muschelli,

Thanks a lot,  it's really helpful! I will open an issue by following the instruction.

Thanks
Chaoli

________________________________
