### ISSUE TITLE
WhiteStripe not available

### ISSUE THREAD

**Issue by SJ-cog** [muschellij2/extrantsr#15]
Hi,
I have been trying to install extrantsr however I am getting the message that WhiteSteipe is not available for this package. I tried to install extrantsr a couple different ways but each time it gives me an error message related to WhiteStripe. Is there ea way around this issue. Any help will be much appreciated. 

Here is an example of the error message

> devtools::install_github("muschellij2/extrantsr", dependencies=FALSE)
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo muschellij2/extrantsr@HEAD
   checking DESCRIPTION meta-information ...9/t6v_ztjs77x1w1dhxkf81wbw0000gq/T/Rtmp5dzQM7/remotesea403c89e53f/muschellij2-extrantsr-eb0730e/DESCRIPTION’ ...
Installing package into ‘/Users/shijain/Library/R/4.1/library’
(as ‘lib’ is unspecified)
ERROR: dependency ‘WhiteStripe’ is not available for package ‘extrantsr’
* removing ‘/Users/shijain/Library/R/4.1/library/extrantsr’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/q9/t6v_ztjs77x1w1dhxkf81wbw0000gq/T//Rtmp5dzQM7/fileea40129aa26/extrantsr_3.9.13.1.tar.gz’ had non-zero exit status

**Comment by muschellij2** [comment]
`remotes::install_github("https://github.com/muschellij2/WhiteStripe")`

**Comment by SJ-cog** [comment]
thank you, this worked!
