### ISSUE TITLE
Cannot install: cannot open URL

### ISSUE THREAD

**Issue by chewnglow** [muschellij2/extrantsr#8]
I'm using devtools 2.0.1 on R 3.5.1. When follow the instruction the devtools says `cannot open URL'https://api.github.com/repos/muschellij2/extrantsr/tarball/master'`.

**Comment by muschellij2** [comment]
May be a temporary problem with github.  Please try again as
```r
devtools::install_github("muschellij2/extrantsr")
```
worked fine for me.
